spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - profile_nickname
              - account_email
          naver:
            client-name: Naver
            client-id: c835aJO2LkM9iRMe9o3J
            client-secret: ahsheXjmgh
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-id: 282364161730-btrf80j54eos76v9kcvvjge4tlqoormf.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response