sys:
  version: 0.1.0

spring:
  profiles:
    group:
      "local" : "local"
    active : ${SPRING_PROFILES_ACTIVE}

  config:
    import:
      - classpath:/application-jwt.yml
      - classpath:/application-oauth.yml

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---
spring:
  config:
    activate:
      on-profile: "local"


  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sosim_re_test?serverTimezone=Asia/Seoul
      username: sosim_jean
      password: sosim_1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update #create #create-drop #update #create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
#        show-sql: true
#        format_sql: true
        globally_quoted_identifiers: true

  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace