spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: f17f6d56ad837b715fd34160ac7b21f4
            client-secret: hQFRF2bx9LQyrP3CErKUMVE7MJAEBpmI
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - profile_nickname
              - account_email
          naver:
            client-name: Naver
            client-id: c835aJO2LkM9iRMe9o3J
            client-secret: ahsheXjmgh
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-id: 282364161730-btrf80j54eos76v9kcvvjge4tlqoormf.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            #            user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response