spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: b504b366fdc46909d2b6e779678b91b4
            client-secret: AShX5BjsnXJDxhwPAxETDGe1O0sXicKF
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: client-app
            scope:
              - profile_nickname
              - account_email
          naver:
            client-name: Naver
            client-id: c835aJO2LkM9iRMe9o3J
            client-secret: ahsheXjmgh
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-id: 139006585224-i1rbb77sro3ghh8ab636cdclm49fo62c.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            #            user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response