sys.version: 0.1.0

spring:
  profiles:
    active:
      - dev
  application:
    name: sosim
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sosim?serverTimezone=Asia/Seoul
    username: sosim_jean
    password: sj1234
  jpa:
    hibernate:
      ddl-auto: update #create none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false